local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0

  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  static_layer:
    enabled: true
    map_topic: "/map"

  inflation_layer:
    enabled: true
    cost_scaling_factor: 5
    inflation_radius: 0.3

  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: 
      topic: /scan
      sensor_frame: base_link
      data_type: LaserScan
      clearing: true
      marking: true
      obstacle_range: 3.0
      raytrace_range: 4.0
